(function(){
 'use strict';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let contracts=[
 {id:'SF-1405-001',customer:'شرکت نمونه آریا',title:'اشتراک سازمانی پارامتر',start:'۱۴۰۵/۰۱/۱۵',end:'۱۴۰۶/۰۱/۱۵',amount:480000000,status:'فعال',license:'LIC-001',users:'۲۵'},
 {id:'SF-1405-002',customer:'مهندسین مشاور نمونه',title:'پلن حرفه‌ای سالانه',start:'۱۴۰۵/۰۳/۰۱',end:'۱۴۰۶/۰۳/۰۱',amount:240000000,status:'فعال',license:'LIC-002',users:'۱۰'},
 {id:'SF-1405-003',customer:'گروه ساختمانی نمونه',title:'اشتراک پایه',start:'۱۴۰۵/۰۶/۰۱',end:'۱۴۰۶/۰۶/۰۱',amount:120000000,status:'پیش‌نویس',license:'',users:'۵'},
 {id:'SF-1404-004',customer:'شرکت نمونه توسعه',title:'تمدید اشتراک سازمانی',start:'۱۴۰۴/۰۱/۰۱',end:'۱۴۰۵/۰۱/۰۱',amount:360000000,status:'خاتمه‌یافته',license:'LIC-004',users:'۲۰'}];
 try{const saved=JSON.parse(localStorage.getItem('parameter.admin.sales.v1'));if(Array.isArray(saved))contracts=saved}catch{}
 const money=n=>Number(n).toLocaleString('fa-IR');
 const paths={view:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7-10-7-10-7Z"/><circle cx="12" cy="12" r="3"/>',edit:'<path d="m15 4 5 5M4 20l5-1L21 7l-5-5L4 14v6Z"/>',delete:'<path d="M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15"/>',docs:'<path d="M3 6h7l2 3h9v11H3V6ZM8 13h8M12 10v7"/>'};
 const icon=k=>'<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true">'+paths[k]+'</svg>';
 const action=(k,label,id)=>'<button type="button" class="sales-icon" data-action="'+k+'" data-id="'+esc(id)+'" title="'+label+'" aria-label="'+label+'">'+icon(k)+'</button>';
 window.parameterAdminSales=function(d,dashboard,goSales){
  const host=d.getElementById('admin-content');let query='';
  if(!d.getElementById('sales-style')){const st=d.createElement('style');st.id='sales-style';st.textContent='.sales-icon{border:0!important;background:transparent!important;color:#4D49FF!important;padding:5px;cursor:pointer;box-shadow:none!important}.sales-actions{display:flex;gap:5px}.sales-kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:16px;margin:18px 0}.sales-kpi{padding:22px;background:white;border:1px solid #DCE8EC;border-radius:16px}.sales-kpi strong{display:block;font-size:25px;color:#4D49FF;margin-top:14px}.sales-button{font:inherit;border:0;border-radius:10px;background:#4D49FF;color:#fff;padding:10px 16px;cursor:pointer}.sales-note{font-size:11px;color:#697C88;margin:15px 0}.sales-dialog{width:min(560px,94vw);border:1px solid #DCE8EC;border-radius:16px;padding:24px;color:#242540;font:inherit}.sales-dialog::backdrop{background:#24254055}.sales-dialog label{display:grid;gap:6px;margin:12px 0}.sales-dialog input,.sales-dialog select{font:inherit;padding:9px;border:1px solid #DCE8EC;border-radius:8px}.sales-dialog footer{display:flex;gap:12px;margin-top:20px}.sales-dialog button{font:inherit;cursor:pointer}.sales-dialog [role=alert]{color:#4D49FF}';d.head.appendChild(st)}
  function persist(next){try{localStorage.setItem('parameter.admin.sales.v1',JSON.stringify(next));contracts=next;return true}catch{return false}}
  function modal(title,body){const dialog=d.createElement('dialog');dialog.className='sales-dialog';dialog.setAttribute('aria-label',title);dialog.innerHTML='<h2>'+title+'</h2>'+body;d.body.appendChild(dialog);const previous=d.activeElement;dialog.onclose=()=>{dialog.remove();if(previous?.isConnected)previous.focus()};dialog.showModal();return dialog}
  function edit(row,readOnly){const fields=[['customer','مشتری'],['title','موضوع قرارداد'],['start','تاریخ شروع'],['end','تاریخ پایان'],['amount','مبلغ (ریال)']];const dialog=modal(readOnly?'مشاهده قرارداد':'ویرایش قرارداد','<form>'+fields.map(([key,label])=>'<label>'+label+'<input name="'+key+'" value="'+esc(row[key])+'" '+(key==='amount'?'type="number" min="0" step="1"':'')+' required '+(readOnly?'readonly':'')+'></label>').join('')+'<label>وضعیت<select name="status" '+(readOnly?'disabled':'')+'>'+['فعال','پیش‌نویس','خاتمه‌یافته'].map(s=>'<option '+(s===row.status?'selected':'')+'>'+s+'</option>').join('')+'</select></label><p role="alert"></p><footer>'+(readOnly?'':'<button class="sales-button" type="submit">ذخیره</button>')+'<button type="button" data-close>بستن</button></footer></form>');dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.querySelector('form').onsubmit=e=>{e.preventDefault();if(readOnly)return;const next={...row};fields.forEach(([k])=>next[k]=dialog.querySelector('[name='+k+']').value.trim());next.amount=Number(next.amount);next.status=dialog.querySelector('select').value;if(!persist(contracts.map(r=>r.id===row.id?next:r))){dialog.querySelector('[role=alert]').textContent='ذخیره انجام نشد.';return}dialog.close();render()}}
  function docs(row){d.querySelector('#page-title').textContent='اسناد مرتبط — '+row.id;d.querySelector('.breadcrumb').textContent='پنل ادمین / فروش / '+row.id+' / لایسنس';host.innerHTML='<button class="sales-button" data-back>بازگشت به قراردادهای فروش</button><div class="group-tabs"><button class="group-tab active" aria-selected="true">لایسنس</button></div><p>'+esc(row.customer)+' · '+esc(row.title)+'</p><div class="board-wrap"><table class="admin-table"><thead><tr>'+['شماره لایسنس','قرارداد فروش','تعداد کاربران','تاریخ شروع','تاریخ پایان','وضعیت'].map(t=>'<th>'+t+'</th>').join('')+'</tr></thead><tbody>'+(row.license?'<tr>'+[row.license,row.id,row.users,row.start,row.end,row.status].map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>':'<tr><td colspan="6" class="admin-empty">برای این قرارداد لایسنسی صادر نشده است.</td></tr>')+'</tbody></table></div>';host.querySelector('[data-back]').onclick=render}
  function table(){const rows=contracts.filter(r=>Object.values(r).join(' ').includes(query));return '<div class="board-wrap"><table class="admin-table"><thead><tr>'+['ردیف','شماره قرارداد','مشتری','موضوع قرارداد','تاریخ شروع','تاریخ پایان','مبلغ (ریال)','وضعیت','اسناد مرتبط','عملیات'].map(t=>'<th>'+t+'</th>').join('')+'</tr></thead><tbody>'+rows.map((r,i)=>'<tr>'+[i+1,r.id,r.customer,r.title,r.start,r.end,money(r.amount),r.status].map(v=>'<td>'+esc(v)+'</td>').join('')+'<td>'+'<button type="button" class="related-label" data-action="docs" data-id="'+esc(r.id)+'">اسناد مرتبط</button>'+'</td><td><div class="sales-actions">'+action('view','مشاهده',r.id)+action('edit','ویرایش',r.id)+action('delete','حذف',r.id)+'</div></td></tr>').join('')+(rows.length?'':'<tr><td colspan="10" class="admin-empty">نتیجه‌ای یافت نشد.</td></tr>')+'</tbody></table></div>'}
  function bind(){host.querySelector('tbody').onclick=e=>{const b=e.target.closest('[data-action]');if(!b)return;const r=contracts.find(r=>r.id===b.dataset.id);if(!r)return;if(b.dataset.action==='docs')docs(r);else if(b.dataset.action==='delete'){const dialog=modal('حذف قرارداد','<p>قرارداد '+esc(r.id)+' و لایسنس وابسته به آن حذف شود؟</p><p role="alert"></p><footer><button class="sales-button" data-confirm>حذف</button><button data-cancel>انصراف</button></footer>');dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.querySelector('[data-confirm]').onclick=()=>{if(!persist(contracts.filter(x=>x.id!==r.id))){dialog.querySelector('[role=alert]').textContent='حذف ذخیره نشد.';return}dialog.close();render()}}else edit(r,b.dataset.action==='view')}}
  function render(){d.querySelector('#page-title').textContent='قرارداد فروش';d.querySelector('.breadcrumb').textContent='پنل ادمین / فروش / قرارداد فروش';host.innerHTML='<div class="group-tabs"><button class="group-tab active" aria-selected="true">قرارداد فروش</button></div><div class="admin-toolbar"><input type="search" aria-label="جستجوی قراردادها" placeholder="جستجوی قرارداد…" value="'+esc(query)+'"></div><div data-table>'+table()+'</div><p class="sales-note">داده‌های نمونه · تغییرات در همین مرورگر ذخیره می‌شود.</p>';host.querySelector('input').oninput=e=>{query=e.target.value;host.querySelector('[data-table]').innerHTML=table();bind()};bind()}
  if(dashboard){host.innerHTML='<div class="sales-kpis">'+[['قراردادهای فروش',contracts.length],['قراردادهای فعال',contracts.filter(r=>r.status==='فعال').length],['لایسنس‌های صادرشده',contracts.filter(r=>r.license).length],['ارزش قراردادها (ریال)',contracts.reduce((n,r)=>n+r.amount,0)]].map(([label,n])=>'<div class="sales-kpi">'+label+'<strong>'+money(n)+'</strong></div>').join('')+'</div><button class="sales-button" data-sales>مشاهده قراردادهای فروش</button><p class="sales-note">شاخص‌ها بر اساس قراردادهای نمونهٔ همین پنل هستند.</p>';host.querySelector('[data-sales]').onclick=goSales}else render();
 };
})();
