(function(){
  'use strict';
  var installed=new WeakSet(),panel=null;
  var styles='.pmc-head{position:relative!important;padding-inline:8px 32px!important}.pmc-head .th-tools,.pmc-head .th-sort-btn,.pmc-head .pmc-sort-toggle,.pmc-head .pmc-sort-mark{display:none!important}.pmc-head>.pmc-trigger{display:grid!important;place-items:center!important;position:absolute!important;inset-inline-start:auto!important;inset-inline-end:5px!important;top:50%!important;transform:translateY(-50%)!important;width:24px!important;height:26px!important;padding:0!important;border:0!important;border-radius:5px!important;background:transparent!important;color:#568cc8!important;cursor:pointer!important}.pmc-trigger svg{width:13px!important;height:13px!important;fill:currentColor!important}.pmc-trigger:hover,.pmc-trigger.pmc-active{background:#e5f1ff!important;color:#0073ea!important}.pmc-popover{position:fixed!important;z-index:15000!important;padding:8px!important;border:1px solid #d0d4e4!important;border-radius:8px!important;background:#fff!important;color:#323338!important;box-shadow:0 8px 24px #172b4d26!important;direction:rtl;font:inherit}.pmc-popover .pmc-order{display:block;width:100%;padding:9px;border:0;border-radius:5px;text-align:start;background:white;color:#323338;font:inherit;font-size:12px;cursor:pointer}.pmc-popover .pmc-order:hover,.pmc-popover .pmc-order[aria-pressed=true]{background:#e5f1ff;color:#0073ea}.pmc-popover input{box-sizing:border-box;width:100%;height:34px;margin-top:7px;padding:6px 9px;border:1px solid #c3c6d4;border-radius:5px;font:inherit;font-size:12px}.pmc-popover .pmc-clear{margin-top:5px;color:#676879}.pmc-popover button:focus-visible,.pmc-trigger:focus-visible{outline:2px solid #0073ea!important}';
  function clean(v){return String(v==null?'':v).replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/[۰-۹]/g,function(c){return '۰۱۲۳۴۵۶۷۸۹'.indexOf(c)}).replace(/[٠-٩]/g,function(c){return '٠١٢٣٤٥٦٧٨٩'.indexOf(c)}).replace(/\s+/g,' ').trim().toLowerCase()}
  function label(th){var c=th.cloneNode(true);c.querySelectorAll('.th-tools,.th-sort-btn,.pmc-trigger,.pmc-sort-toggle,.pmc-sort-mark').forEach(function(n){n.remove()});return (c.textContent||th.getAttribute('data-label')||th.getAttribute('aria-label')||'').trim()}
  function value(row,th){var cell=row.cells[th.cellIndex];if(!cell)return '';var explicit=cell.getAttribute('data-sort-value')||cell.getAttribute('data-filter-value');if(explicit!==null)return clean(explicit);var controls=cell.querySelectorAll('input:not([type=hidden]),select,textarea');if(controls.length)return clean(Array.from(controls).map(function(c){return c.tagName==='SELECT'?Array.from(c.selectedOptions).map(function(o){return o.textContent}).join(' '):c.value}).join(' '));var count=cell.querySelector('.count');if(count)return clean(count.textContent);var text=clean(cell.innerText||cell.textContent);if(text)return text;return clean(Array.from(cell.querySelectorAll('[aria-label],[title],[data-tip]')).map(function(e){return e.getAttribute('aria-label')||e.getAttribute('title')||e.getAttribute('data-tip')}).join(' '))}
  function numeric(v){var n=v.replace(/[,٬،]/g,'').replace(/٫/g,'.');return /^-?\d+(\.\d+)?$/.test(n)?Number(n):null}
  function state(table){if(!table.__pmcUnified)table.__pmcUnified={filters:new Map(),sort:null,dir:'',order:new WeakMap(),counter:0};return table.__pmcUnified}
  function dataRow(row){return !row.classList.contains('pmc-no-results')&&Array.from(row.cells).every(function(c){return c.colSpan===1})}
  function apply(table){var s=state(table);table.querySelectorAll('thead .pmc-trigger').forEach(function(b){var th=b.closest('th');b.classList.toggle('pmc-active',!!s.filters.get(th)||s.sort===th);th.setAttribute('aria-sort',s.sort===th?(s.dir==='asc'?'ascending':'descending'):'none')});
    Array.from(table.tBodies).forEach(function(body){var rows=Array.from(body.rows);rows.filter(dataRow).forEach(function(row){if(!s.order.has(row))s.order.set(row,s.counter++);var show=Array.from(s.filters).every(function(pair){return !pair[1]||value(row,pair[0]).includes(clean(pair[1]))});var display=show?'':'none';if(row.style.display!==display)row.style.display=display});
      // Sort each contiguous data group in its own tbody; do not move group headings or totals.
      var groups=[],group=[];rows.forEach(function(r){if(dataRow(r))group.push(r);else{if(group.length)groups.push({rows:group,end:r});group=[]}});if(group.length)groups.push({rows:group,end:null});
      groups.forEach(function(g){var sorted=g.rows.slice().sort(function(a,b){if(!s.sort||!s.dir)return s.order.get(a)-s.order.get(b);var av=value(a,s.sort),bv=value(b,s.sort),an=numeric(av),bn=numeric(bv),cmp=an!==null&&bn!==null?an-bn:av.localeCompare(bv,'fa',{numeric:true,sensitivity:'base'});return (s.dir==='desc'?-cmp:cmp)||s.order.get(a)-s.order.get(b)});if(sorted.some(function(r,i){return r!==g.rows[i]}))sorted.forEach(function(r){body.insertBefore(r,g.end)})});
    });
  }
  function close(){if(panel){if(panel._trigger)panel._trigger.setAttribute('aria-expanded','false');panel.remove();panel=null}}
  function open(table,th,trigger,doc){if(panel&&panel._trigger===trigger){close();return}close();var s=state(table),p=doc.createElement('div');panel=p;p._trigger=trigger;p.className='pmc-popover';p.setAttribute('role','dialog');p.setAttribute('aria-label','مرتب‌سازی و فیلتر '+label(th));trigger.setAttribute('aria-expanded','true');
    [['asc','مرتب‌سازی صعودی ↑'],['desc','مرتب‌سازی نزولی ↓'],['','حذف مرتب‌سازی']].forEach(function(item){var b=doc.createElement('button');b.type='button';b.className='pmc-order';b.textContent=item[1];b.setAttribute('aria-pressed',String(s.sort===th&&s.dir===item[0]));b.onclick=function(){s.sort=item[0]?th:null;s.dir=item[0];apply(table);close();trigger.focus()};p.appendChild(b)});
    var input=doc.createElement('input');input.type='search';input.placeholder='فیلتر این ستون…';input.setAttribute('aria-label','فیلتر '+label(th));input.value=s.filters.get(th)||'';input.oninput=function(){s.filters.set(th,input.value);apply(table)};p.appendChild(input);
    var clear=doc.createElement('button');clear.type='button';clear.className='pmc-order pmc-clear';clear.textContent='پاک‌کردن فیلتر';clear.onclick=function(){s.filters.delete(th);input.value='';apply(table);input.focus()};p.appendChild(clear);
    p.addEventListener('keydown',function(e){if(e.key==='Escape'){close();trigger.focus()}});doc.body.appendChild(p);var r=trigger.getBoundingClientRect(),width=Math.min(250,doc.defaultView.innerWidth-16);p.style.width=width+'px';p.style.boxSizing='border-box';p.style.left=Math.max(8,Math.min(r.right-width,doc.defaultView.innerWidth-width-8))+'px';p.style.top=Math.max(8,r.bottom+p.offsetHeight+5>doc.defaultView.innerHeight?r.top-p.offsetHeight-5:r.bottom+5)+'px';input.focus();
  }
  function enhance(table,doc){if(!table.tHead)return;Array.from(table.tHead.rows).forEach(function(row){Array.from(row.cells).forEach(function(th){if(th.colSpan>1)return;var name=label(th);if(!name||/^(عملیات|actions?|operations)$/i.test(clean(name)))return;th.classList.add('pmc-head');th.querySelectorAll('.pmc-sort-toggle,.pmc-sort-mark').forEach(function(n){n.remove()});if(th.querySelector('.pmc-trigger[data-unified]'))return;th.querySelectorAll('.pmc-trigger').forEach(function(n){n.remove()});var b=doc.createElement('button');b.type='button';b.className='pmc-trigger';b.dataset.unified='true';b.setAttribute('aria-label','مرتب‌سازی و فیلتر '+name);b.setAttribute('aria-expanded','false');b.setAttribute('aria-haspopup','dialog');b.innerHTML='<svg viewBox="0 0 12 12" aria-hidden="true"><circle cx="6" cy="2" r="1.3"/><circle cx="6" cy="6" r="1.3"/><circle cx="6" cy="10" r="1.3"/></svg>';b.onclick=function(e){e.preventDefault();e.stopPropagation();open(table,th,b,doc)};th.appendChild(b)})});apply(table)}
  // Match the plan header: independent sort and an inline column filter, no menu.
  enhance=function(table,doc){if(!table.tHead)return;Array.from(table.tHead.rows).forEach(function(row){Array.from(row.cells).forEach(function(th){if(th.colSpan>1)return;var name=label(th);if(!name||/^(عملیات|فرم‌های مرتبط|فرم های مرتبط|actions?|operations)$/i.test(clean(name)))return;if(th.querySelector('.pmc-inline-tools'))return;th.classList.add('pmc-head');th.querySelectorAll('.pmc-trigger,.pmc-sort-toggle,.pmc-sort-mark').forEach(function(n){n.remove()});var controls=doc.createElement('span');controls.className='pmc-inline-tools';var sort=doc.createElement('button');sort.type='button';sort.title='مرتب‌سازی '+name;sort.setAttribute('aria-label',sort.title);sort.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="m5 8 3-3 3 3M8 5v14m5-3 3 3 3-3M16 19V5"/></svg>';sort.onclick=function(e){e.stopPropagation();var s=state(table);s.dir=s.sort!==th?'asc':s.dir==='asc'?'desc':s.dir==='desc'?'':'asc';s.sort=s.dir?th:null;apply(table);sort.setAttribute('aria-label','مرتب‌سازی '+name+' '+(s.dir==='asc'?'صعودی':s.dir==='desc'?'نزولی':'بدون ترتیب'));th.setAttribute('aria-sort',s.dir==='asc'?'ascending':s.dir==='desc'?'descending':'none')};var filter=doc.createElement('button');filter.type='button';filter.title='فیلتر '+name;filter.setAttribute('aria-label',filter.title);filter.setAttribute('aria-expanded','false');filter.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M3 4h18l-7 8v7l-4 2V12z"/></svg>';var input=doc.createElement('input');input.type='search';input.className='pmc-inline-filter';input.hidden=true;input.placeholder='فیلتر این ستون…';input.setAttribute('aria-label',filter.title);input.onclick=function(e){e.stopPropagation()};input.oninput=function(){state(table).filters.set(th,input.value);apply(table)};filter.onclick=function(e){e.stopPropagation();input.hidden=!input.hidden;filter.setAttribute('aria-expanded',String(!input.hidden));if(!input.hidden)input.focus()};controls.appendChild(filter);controls.appendChild(sort);th.appendChild(controls);th.appendChild(input)})});apply(table)};
  styles+=' .pmc-head{padding-inline:8px 55px!important}.pmc-inline-tools{position:absolute;inset-inline-end:5px;top:8px;display:flex;gap:2px}.pmc-inline-tools button{border:0!important;box-shadow:none!important;background:transparent!important;padding:2px!important;width:20px;height:22px;color:#9aa1b1;cursor:pointer}.pmc-inline-tools svg{width:16px;height:16px}.pmc-inline-tools button:hover{color:#087bf0}.pmc-inline-filter{box-sizing:border-box;width:100%;min-width:60px;margin-top:6px;padding:5px 8px;border:1px solid #d0d4e4;border-radius:7px;font:inherit;font-size:11px}.pmc-inline-filter[hidden]{display:none!important}';
  function scan(doc){doc.querySelectorAll('table').forEach(function(t){enhance(t,doc)});doc.querySelectorAll('iframe').forEach(function(f){try{if(f.contentDocument)install(f.contentDocument);if(!f.__pmcLoad){f.__pmcLoad=true;f.addEventListener('load',function(){try{install(f.contentDocument)}catch(e){}})}}catch(e){}})}
  function install(doc){if(!doc||!doc.documentElement||installed.has(doc))return;installed.add(doc);var style=doc.createElement('style');style.id='parameter-unified-columns-style';style.textContent=styles;(doc.head||doc.documentElement).appendChild(style);var pending;function schedule(){if(pending)return;pending=setTimeout(function(){pending=null;scan(doc)},80)}new doc.defaultView.MutationObserver(schedule).observe(doc.documentElement,{childList:true,subtree:true});doc.addEventListener('click',function(e){if(panel&&!panel.contains(e.target)&&!e.target.closest('.pmc-trigger'))close()},true);doc.defaultView.addEventListener('resize',close);doc.defaultView.addEventListener('scroll',function(e){if(panel&&!panel.contains(e.target))close()},true);scan(doc)}
  install(document);
})();
