(function(){
'use strict';
var people=[['علی رضایی','تهیه‌کننده برآورد','مهندسین مشاور هگزا','تهیه و ارسال'],['سارا احمدی','کارشناس فنی','مهندسین مشاور هگزا','کنترل فنی'],['محمد کریمی','مدیر طرح','شرکت فرودگاه‌ها','بررسی و تأیید'],['مریم حسینی','مدیر مالی','شرکت فرودگاه‌ها','کنترل مالی'],['رضا امینی','نماینده کارفرما','شرکت فرودگاه‌ها','بررسی کارفرما'],['نگار محمدی','کارشناس قراردادها','شرکت فرودگاه‌ها','کنترل قراردادی'],['حسین کاظمی','کارشناس حقوقی','شرکت فرودگاه‌ها','بررسی حقوقی'],['بهاره مرادی','مدیر برنامه‌ریزی','شرکت فرودگاه‌ها','تطبیق بودجه'],['امیر موسوی','معاون فنی','شرکت فرودگاه‌ها','تأیید فنی'],['لیلا نادری','مدیرعامل','شرکت فرودگاه‌ها','تصویب نهایی']];
var events=[['۱۴۰۵/۰۶/۱۰','۰۸:۱۵','ایجاد سند',0,0,'ثبت پیش‌نویس اولیه برآورد.'],['۱۴۰۵/۰۶/۱۰','۱۰:۳۰','ارسال',0,1,'ارسال برای کنترل مقادیر و بهای واحد.'],['۱۴۰۵/۰۶/۱۱','۰۹:۴۵','عودت برای اصلاح',1,0,'اصلاح مقادیر فصل عملیات خاکی درخواست شد.'],['۱۴۰۵/۰۶/۱۱','۱۴:۲۰','ارسال مجدد',0,1,'مقادیر اصلاح و مستندات تکمیل شد.'],['۱۴۰۵/۰۶/۱۲','۱۱:۱۰','تأیید و ارسال',1,2,'کنترل فنی انجام شد؛ ارسال برای بررسی مدیر طرح.']];
var root,selected=-1,operation='',query='',opener;
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function person(i){return '<b>'+people[i][0]+'</b><small>'+people[i][1]+' · '+people[i][2]+'</small>'}
function records(){var rows=events.filter(function(e){return(selected<0||e[3]===selected||e[4]===selected)&&(!operation||e[2]===operation)&&(!query||(e.join(' ')+people[e[3]].join(' ')+people[e[4]].join(' ')).includes(query))});root.querySelector('.ew-count').textContent=rows.length+' رویداد';root.querySelector('tbody').innerHTML=rows.slice().reverse().map(function(e){return '<tr><td><b dir="ltr">'+e[0]+'</b><small dir="ltr">'+e[1]+'</small></td><td><span class="ew-badge '+(e[2].includes('عودت')?'returned':'')+'">'+e[2]+'</span></td><td>'+person(e[3])+'</td><td>'+ (e[2]==='ایجاد سند'?'—':person(e[4]))+'</td><td>'+e[5]+'</td></tr>'}).join('')||'<tr><td colspan="5" class="ew-empty">رویدادی با این فیلترها یافت نشد.</td></tr>';root.querySelectorAll('[data-person]').forEach(function(b){b.setAttribute('aria-pressed',String(+b.dataset.person===selected))})}
function icon(path){return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+path+'</svg>'}
function activateTab(key,focus){root.querySelectorAll('[data-ew-tab]').forEach(function(b){var on=b.dataset.ewTab===key;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;if(on&&focus)b.focus()});root.querySelectorAll('[role=tabpanel]').forEach(function(p){p.hidden=p.id!=='ew-panel-'+key})}
window.openParameterEstimateHistory=function(entity,index){
 opener=document.activeElement;var row=(typeof ESTIMATES!=='undefined'&&ESTIMATES[entity]||[])[index]||{};selected=-1;operation='';query='';if(root)root.remove();root=document.createElement('dialog');root.className='ew-dialog';root.dir='rtl';root.setAttribute('aria-labelledby','ew-title');
 var user=icon('<circle cx="12" cy="8" r="3.5"/><path d="M5 21v-3a7 7 0 0 1 14 0v3"/>'),clock=icon('<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'),flow=icon('<circle cx="5" cy="6" r="2"/><circle cx="19" cy="18" r="2"/><path d="M5 8v6a4 4 0 0 0 4 4h8M7 6h12M15 2l4 4-4 4"/>');
 root.innerHTML='<header class="ew-header"><div><h2 id="ew-title">گردش سند</h2><p>برآورد شماره '+esc(row.no||index+1)+' · '+esc(row.kind||'برآورد اجرای کار')+'</p></div><button class="ew-close" aria-label="بستن">×</button></header><div class="ew-content"><nav class="ew-tabs group-tabs" role="tablist" aria-label="گردش سند">'+[['flow','گردش کار',flow],['history','تاریخچه',clock]].map(function(t){return '<button type="button" role="tab" id="ew-tab-'+t[0]+'" data-ew-tab="'+t[0]+'" aria-controls="ew-panel-'+t[0]+'" class="group-tab gt-blue'+(t[0]==='flow'?' active':'')+'" aria-selected="'+(t[0]==='flow')+'" tabindex="'+(t[0]==='flow'?'0':'-1')+'"><span class="parameter-tab-icon">'+t[2]+'</span>'+t[1]+'</button>'}).join('')+'</nav><section id="ew-panel-flow" role="tabpanel" aria-labelledby="ew-tab-flow"><div class="ew-flow-meta"><span>۱۰ مرحله</span><span>۱۰ نفر</span><span>۲ سازمان</span></div><div class="ew-flow-scroll" tabindex="0" role="region" aria-label="مسیر ۱۰ مرحله‌ای گردش سند"><div class="ew-flow">'+people.map(function(p,i){return '<div class="ew-step '+(i<2?'done':i===2?'current':'pending')+'" '+(i===2?'aria-current="step"':'')+'><div class="ew-owner-label">'+(i===2?'سند اینجاست':'')+'</div><div class="ew-avatar">'+user+'<span class="ew-number">'+(i<2?'✓':String(i+1).replace(/\d/g,function(n){return '۰۱۲۳۴۵۶۷۸۹'[n]}))+'</span>'+(i===2?'<span class="ew-document">'+icon('<path d="M7 3h7l4 4v14H7zM14 3v5h4M10 12h5M10 16h5"/>')+'</span>':'')+'</div><strong>'+p[0]+'</strong><span>'+p[1]+'</span><small>'+p[2]+'</small><div class="ew-stage">'+p[3]+'</div></div>'}).join('')+'</div></div><div class="ew-flow-footer"><span class="ew-state"><i></i>در انتظار بررسی مدیر طرح</span><time>۱۴۰۵/۰۶/۱۲ · ۱۱:۱۰</time></div></section><section id="ew-panel-history" role="tabpanel" aria-labelledby="ew-tab-history" hidden><div class="ew-filters"><input type="search" placeholder="جستجو…" aria-label="جستجوی تاریخچه"><select class="ew-person-filter" aria-label="شخص"><option value="-1">همه افراد</option>'+people.map(function(p,i){return '<option value="'+i+'">'+p[0]+'</option>'}).join('')+'</select><select class="ew-operation-filter" aria-label="نوع عملیات"><option value="">همه عملیات</option>'+events.map(function(e){return '<option>'+e[2]+'</option>'}).join('')+'</select><span class="ew-count"></span></div><div class="ew-table"><table><thead><tr><th>تاریخ و ساعت</th><th>عملیات</th><th>از</th><th>به</th><th>توضیحات</th></tr></thead><tbody></tbody></table></div></section><div class="ew-demo">داده‌های نمونه</div></div>';
 document.body.appendChild(root);root.querySelector('.ew-close').onclick=function(){root.close()};root.addEventListener('close',function(){root.remove();if(opener&&opener.isConnected)opener.focus()});root.querySelectorAll('[data-ew-tab]').forEach(function(b){b.onclick=function(){activateTab(b.dataset.ewTab)};b.onkeydown=function(e){if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();activateTab(e.key==='Home'?'flow':e.key==='End'?'history':b.dataset.ewTab==='flow'?'history':'flow',true)}}});root.querySelector('input').oninput=function(){query=this.value.trim();records()};root.querySelector('.ew-operation-filter').onchange=function(){operation=this.value;records()};root.querySelector('.ew-person-filter').onchange=function(){selected=+this.value;records()};records();root.showModal();root.querySelector('[data-ew-tab=flow]').focus();
};

document.addEventListener('click',function(e){var button=e.target.closest&&e.target.closest('.ew-trigger');if(!button)return;e.preventDefault();e.stopImmediatePropagation();window.openParameterEstimateHistory(button.dataset.entity,+button.dataset.index)},true);
function attach(){document.querySelectorAll('#view-estimate-list .psub-table,#view-plan-docs .parameter-estimate-table').forEach(function(table){var head=table.querySelector('thead tr');if(head&&!head.querySelector('.ew-actions')){var th=document.createElement('th');th.className='ew-actions';th.textContent='عملیات';head.appendChild(th)}table.querySelectorAll('tbody tr.parameter-estimate-row').forEach(function(row,i){if(row.querySelector('.ew-trigger'))return;var td=document.createElement('td');td.className='ew-actions';var b=document.createElement('button');b.className='ew-trigger';b.dataset.entity=table.closest('#view-plan-docs')?planDocsCtx.id:estActiveEntity;b.dataset.index=i;b.title='تاریخچه گردش کار';b.setAttribute('aria-label','تاریخچه گردش کار برآورد '+(i+1));b.innerHTML='<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M3 11a9 9 0 1 1 2.6 7M3 4v7h7M12 7v5l3 2"/></svg>';b.onclick=function(e){e.stopPropagation();window.openParameterEstimateHistory(table.closest('#view-plan-docs')?planDocsCtx.id:estActiveEntity,i)};td.appendChild(b);row.appendChild(td)})})}
var queued=false;new MutationObserver(function(){if(!queued){queued=true;requestAnimationFrame(function(){queued=false;attach()})}}).observe(document.body,{childList:true,subtree:true});attach();
})();
