(function(){
  'use strict';
  var selected='success',root;
  var sample={success:[['192.0.2.18','۱۴۰۵/۰۶/۰۹، ۱۰:۰۱:۲۸'],['192.0.2.18','۱۴۰۵/۰۶/۰۸، ۱۸:۵۸:۱۳'],['192.0.2.24','۱۴۰۵/۰۶/۰۷، ۱۴:۲۵:۲۳']],failed:[['192.0.2.18','۱۴۰۵/۰۶/۰۸، ۱۸:۵۷:۲۹','نام کاربری یا رمز عبور اشتباه است.'],['192.0.2.24','۱۴۰۵/۰۶/۰۷، ۱۴:۲۴:۰۶','نام کاربری یا رمز عبور اشتباه است.']]};
  function tab(key,label,path){var on=selected===key;return '<button type="button" class="group-tab'+(on?' active':'')+'" data-login-tab="'+key+'" aria-pressed="'+on+'" aria-selected="'+on+'"><span class="parameter-tab-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8">'+path+'</svg></span><span>'+label+'</span></button>'}
  function render(){var failed=selected==='failed',headers=['ردیف','IP','زمان (تاریخ و ساعت)'].concat(failed?['پیام خطا']:[]);root.innerHTML='<div class="lh-command"><nav aria-label="نوع ورود">'+tab('success','ورود موفق','<path d="m5 12 4 4L19 6"/>')+tab('failed','ورود ناموفق','<path d="m6 6 12 12M18 6 6 18"/>')+'</nav><small>داده‌های نمونه</small></div><div class="lh-table-wrap"><table class="data-table"><caption class="lh-sr">'+(failed?'ورود ناموفق':'ورود موفق')+'</caption><thead><tr>'+headers.map(function(h){return '<th scope="col">'+h+'</th>'}).join('')+'</tr></thead><tbody>'+sample[selected].map(function(row,i){return '<tr><td>'+String(i+1).replace(/\d/g,function(n){return '۰۱۲۳۴۵۶۷۸۹'[n]})+'</td>'+row.map(function(value,index){return '<td'+(index<2?' dir="ltr"':'')+'>'+value+'</td>'}).join('')+'</tr>'}).join('')+'</tbody></table></div>';root.querySelectorAll('[data-login-tab]').forEach(function(b){b.onclick=function(){selected=b.dataset.loginTab;render();root.querySelector('[data-login-tab="'+selected+'"]').focus({preventScroll:true})}})}
  function fit(){if(root&&root.isConnected)root.style.height=Math.max(180,innerHeight-root.getBoundingClientRect().top-24)+'px'}
  window.openParameterLoginHistory=function(){if(typeof showView==='function')showView('placeholder');var host=document.getElementById('view-placeholder');if(!host)return;host.innerHTML='<section class="lh-root" dir="rtl" aria-label="سوابق ورود"></section>';root=host.firstElementChild;selected='success';var title=document.getElementById('page-title'),crumb=document.getElementById('page-breadcrumb');if(title)title.textContent='سوابق ورود';if(crumb)crumb.textContent='کاربر / سوابق ورود';render();fit()};
  window.addEventListener('resize',fit);
})();
