(function(){
 'use strict';var panel,previous;
 function close(){if(panel){panel.querySelectorAll('input[type=password],input[data-secret]').forEach(function(i){i.value=''});panel.remove();panel=null}if(previous&&previous.isConnected)previous.focus({preventScroll:true})}
 window.openParameterPassword=function(){close();previous=document.activeElement;if(typeof window.showView==='function')window.showView('placeholder');var host=document.getElementById('view-placeholder');if(!host)return;host.textContent='';panel=document.createElement('section');panel.className='parameter-profile-page parameter-password-drawer';panel.dir='rtl';panel.setAttribute('aria-label','پروفایل');var title=document.getElementById('page-title'),crumb=document.getElementById('page-breadcrumb');if(title)title.textContent='پروفایل';if(crumb)crumb.textContent='کاربر / پروفایل';
 var eye='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12z"/><circle cx="12" cy="12" r="3"/></svg>';
 function secret(name,label,auto){return '<label class="pwd-label" for="pwd-'+name+'">'+label+' <span aria-hidden="true">*</span></label><div class="pwd-input"><input id="pwd-'+name+'" name="'+name+'" data-secret type="password" autocomplete="'+auto+'" required '+(name==='current'?'':'minlength="10" maxlength="11"')+'><button type="button" data-toggle="'+name+'" aria-label="نمایش '+label+'" title="نمایش '+label+'" aria-pressed="false">'+eye+'</button></div>'}
 panel.innerHTML='<header><h2>تغییر رمز عبور</h2><button type="button" data-close aria-label="بستن فرم">×</button></header><div class="pud-body"><form><label class="pwd-label" for="pwd-user">نام کاربری</label><input id="pwd-user" name="username" autocomplete="username" readonly><div class="pwd-fields">'+secret('current','رمز فعلی','current-password')+secret('next','رمز جدید','new-password')+'<ul class="pwd-rules" aria-live="polite"><li data-rule="min">حداقل طول رمز عبور: ۱۰</li><li data-rule="max">حداکثر طول رمز عبور: ۱۱</li><li data-rule="digit">حداقل یک عدد</li></ul>'+secret('repeat','تکرار رمز جدید','new-password')+'<p class="pwd-match" aria-live="polite"></p></div><p class="pud-note">نمونه طراحی؛ بررسی رمز فعلی و تغییر واقعی رمز نیازمند اتصال سرویس است.</p><p class="pwd-result" role="status"></p><footer><button class="pud-save" type="submit" disabled>ثبت</button><button type="button" data-close>انصراف</button></footer></form></div>';
 panel.querySelector('header h2').textContent='پروفایل';panel.querySelector('header [data-close]').textContent='بازگشت';panel.querySelector('header [data-close]').setAttribute('aria-label','بازگشت');host.appendChild(panel);var form=panel.querySelector('form'),f=form.elements;
 try{var input=window.top.document.getElementById('user');f.username.value=input?input.value:''}catch(e){}if(!f.username.value)f.username.placeholder='نام کاربری نشست در دسترس نیست';
 function validate(){var v=f.next.value,tests={min:v.length>=10,max:v.length>0&&v.length<=11,digit:/[0-9۰-۹٠-٩]/.test(v)};Object.keys(tests).forEach(function(k){panel.querySelector('[data-rule='+k+']').classList.toggle('valid',tests[k])});var match=!!f.repeat.value&&f.repeat.value===v;panel.querySelector('.pwd-match').textContent=f.repeat.value?(match?'تکرار رمز مطابقت دارد.':'تکرار رمز با رمز جدید یکسان نیست.') :'';panel.querySelector('.pwd-match').classList.toggle('valid',match);form.querySelector('[type=submit]').disabled=!(f.current.value&&tests.min&&tests.max&&tests.digit&&match);return !form.querySelector('[type=submit]').disabled}
 form.addEventListener('input',function(){panel.querySelector('.pwd-result').textContent='';validate()});panel.querySelectorAll('[data-close]').forEach(function(b){b.onclick=function(){close();if(typeof window.showView==='function')window.showView('dashboard')}});panel.querySelectorAll('[data-toggle]').forEach(function(b){b.onclick=function(){var i=f[b.dataset.toggle],show=i.type==='password';i.type=show?'text':'password';b.setAttribute('aria-pressed',String(show));b.setAttribute('aria-label',(show?'پنهان‌کردن':'نمایش')+' رمز');b.title=b.getAttribute('aria-label')}});
 form.onsubmit=function(e){e.preventDefault();if(!validate())return;panel.querySelector('.pwd-result').textContent='ورودی‌ها معتبرند؛ رمز عبور تغییر نکرده است، چون سرویس متصل نیست.';['current','next','repeat'].forEach(function(k){f[k].value='';f[k].type='password'});panel.querySelectorAll('[data-toggle]').forEach(function(b){b.setAttribute('aria-pressed','false');b.setAttribute('aria-label','نمایش رمز');b.title='نمایش رمز'});validate()};f.current.focus({preventScroll:true});
 };
})();
