(function(){
 'use strict';var panel,previous;
 function close(){if(panel){panel.querySelectorAll('input[type=password],input[data-secret]').forEach(function(i){i.value=''});panel.remove();panel=null}if(previous&&previous.isConnected)previous.focus({preventScroll:true})}
 window.openParameterPassword=function(){close();previous=document.activeElement;if(window.I18N){if(I18N.fa)I18N.fa.sidebar_change_password='پروفایل';if(I18N.en)I18N.en.sidebar_change_password='Profile';if(I18N.ar)I18N.ar.sidebar_change_password='الملف الشخصي'}document.querySelectorAll('[data-i18n="sidebar_change_password"]').forEach(function(n){n.textContent=window.currentLang==='en'?'Profile':window.currentLang==='ar'?'الملف الشخصي':'پروفایل'});if(typeof window.showView==='function')window.showView('placeholder');var host=document.getElementById('view-placeholder');if(!host)return;host.textContent='';panel=document.createElement('section');panel.className='parameter-profile-page parameter-password-drawer';panel.dir='rtl';panel.setAttribute('aria-label','پروفایل');var title=document.getElementById('page-title'),crumb=document.getElementById('page-breadcrumb');if(title)title.textContent='پروفایل';if(crumb)crumb.textContent='کاربر / پروفایل';
 var eye='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12z"/><circle cx="12" cy="12" r="3"/></svg>';
 function secret(name,label,auto){return '<div class="pwd-field"><label class="pwd-label" for="pwd-'+name+'">'+label+' <span aria-hidden="true">*</span></label><div class="pwd-input"><input id="pwd-'+name+'" name="'+name+'" data-secret type="password" autocomplete="'+auto+'" required '+(name==='current'?'':'minlength="10" maxlength="11"')+'><button type="button" data-toggle="'+name+'" aria-label="نمایش '+label+'" title="نمایش '+label+'" aria-pressed="false">'+eye+'</button></div></div>'}
 panel.innerHTML='<header><h2>پروفایل</h2><button type="button" data-close aria-label="بازگشت">بازگشت</button></header><div class="profile-content"><section class="profile-summary"><span class="profile-avatar" aria-hidden="true">کاربر</span><div class="profile-identity"><strong class="profile-fullname">کاربر سامانه</strong><span class="profile-username"></span></div><label for="profile-language">زبان<select id="profile-language" name="profileLanguage"><option value="fa">فارسی</option><option value="en">English</option><option value="ar">العربية</option></select></label></section><section class="profile-password-card"><h3>تغییر رمز عبور</h3><form><div class="pwd-fields">'+secret('current','رمز فعلی','current-password')+secret('next','رمز جدید','new-password')+secret('repeat','تکرار رمز جدید','new-password')+'<ul class="pwd-rules" aria-live="polite"><li data-rule="min">حداقل ۱۰ کاراکتر</li><li data-rule="max">حداکثر ۱۱ کاراکتر</li><li data-rule="digit">حداقل یک عدد</li></ul><p class="pwd-match" aria-live="polite"></p></div><p class="pwd-result" role="status"></p><footer><button class="pud-save" type="submit" disabled>ثبت</button><button type="button" data-close>انصراف</button></footer></form></section></div>';
 panel.querySelector('header h2').textContent='پروفایل';panel.querySelector('header [data-close]').textContent='بازگشت';panel.querySelector('header [data-close]').setAttribute('aria-label','بازگشت');host.appendChild(panel);var form=panel.querySelector('form'),f=form.elements;
 var displayName='',username='',avatar;try{var input=window.top.document.getElementById('user');username=input?input.value:''}catch(e){}var nameNode=document.querySelector('.sidebar-user-name'),imageNode=document.querySelector('.sidebar-user-avatar img');displayName=nameNode?nameNode.textContent.trim():'کاربر سامانه';panel.querySelector('.profile-fullname').textContent=displayName;panel.querySelector('.profile-username').textContent=username;avatar=panel.querySelector('.profile-avatar');if(imageNode&&imageNode.src){avatar.textContent='';var image=document.createElement('img');image.src=imageNode.src;image.alt='تصویر '+displayName;avatar.appendChild(image)}else avatar.textContent=displayName.split(/\s+/).map(function(x){return x[0]||''}).slice(0,2).join('');var lang=panel.querySelector('#profile-language');lang.value=window.currentLang||'fa';lang.onchange=function(){if(typeof window.setLang==='function')window.setLang(lang.value)};
 function validate(){var v=f.next.value,tests={min:v.length>=10,max:v.length>0&&v.length<=11,digit:/[0-9۰-۹٠-٩]/.test(v)};Object.keys(tests).forEach(function(k){panel.querySelector('[data-rule='+k+']').classList.toggle('valid',tests[k])});var match=!!f.repeat.value&&f.repeat.value===v;panel.querySelector('.pwd-match').textContent=f.repeat.value?(match?'تکرار رمز مطابقت دارد.':'تکرار رمز با رمز جدید یکسان نیست.') :'';panel.querySelector('.pwd-match').classList.toggle('valid',match);form.querySelector('[type=submit]').disabled=!(f.current.value&&tests.min&&tests.max&&tests.digit&&match);return !form.querySelector('[type=submit]').disabled}
 form.addEventListener('input',function(){panel.querySelector('.pwd-result').textContent='';validate()});panel.querySelectorAll('[data-close]').forEach(function(b){b.onclick=function(){close();if(typeof window.showView==='function')window.showView('dashboard')}});panel.querySelectorAll('[data-toggle]').forEach(function(b){b.onclick=function(){var i=f[b.dataset.toggle],show=i.type==='password';i.type=show?'text':'password';b.setAttribute('aria-pressed',String(show));b.setAttribute('aria-label',(show?'پنهان‌کردن':'نمایش')+' رمز');b.title=b.getAttribute('aria-label')}});
 form.onsubmit=function(e){e.preventDefault();if(!validate())return;panel.querySelector('.pwd-result').textContent='ثبت شد.';['current','next','repeat'].forEach(function(k){f[k].value='';f[k].type='password'});panel.querySelectorAll('[data-toggle]').forEach(function(b){b.setAttribute('aria-pressed','false');b.setAttribute('aria-label','نمایش رمز');b.title='نمایش رمز'});validate()};f.current.focus({preventScroll:true});
 };
})();
