// Extra controls for the portfolio creation form only. Uses the existing pc-control design.
function pcPortfolioExtras(){
  var english=typeof currentLang!=='undefined'&&currentLang==='en';
  var choices=english?['Buildings','Roads and runways','Mechanical installations','Electrical installations','Landscaping']:['ابنیه','راه و باند','تأسیسات مکانیکی','تأسیسات برقی','محوطه‌سازی'];
  function time(kind,label){return '<div class="pf-time"><span>'+label+'</span><div class="pf-clock" dir="ltr"><input class="pc-control" type="text" inputmode="numeric" maxlength="2" data-time="'+kind+'" data-part="hour" aria-label="'+label+' — '+(english?'hour':'ساعت')+'" placeholder="HH" autocomplete="off"><b>:</b><input class="pc-control" type="text" inputmode="numeric" maxlength="2" data-time="'+kind+'" data-part="minute" aria-label="'+label+' — '+(english?'minute':'دقیقه')+'" placeholder="MM" autocomplete="off"></div><input type="hidden" name="'+kind+'Time"></div>'}
  return '<section class="pc-field pc-span pf-extra" aria-label="'+(english?'Time range and activity areas':'بازه زمانی و حوزه‌های فعالیت')+'"><div class="pf-time-range">'+time('from',english?'From time':'از ساعت')+time('to',english?'To time':'تا ساعت')+'</div><small class="pf-hint">'+(english?'24-hour format · optional':'فرمت ۲۴ ساعته · اختیاری')+'</small><p class="pf-time-message" role="status" aria-live="polite"></p><div class="pf-multi"><label id="pf-areas-label">'+(english?'Activity areas':'حوزه‌های فعالیت')+'</label><button type="button" class="pc-control pf-multi-toggle" aria-expanded="false" aria-controls="pf-areas-options" aria-labelledby="pf-areas-label pf-areas-summary"><span id="pf-areas-summary">'+(english?'Select one or more options':'یک یا چند گزینه انتخاب کنید')+'</span><span aria-hidden="true">⌄</span></button><div id="pf-areas-options" class="pf-options" role="group" aria-labelledby="pf-areas-label" hidden>'+choices.map(function(title,i){return '<label><input type="checkbox" name="activityAreas" value="'+i+'"><span>'+title+'</span></label>'}).join('')+'</div><div class="pf-chips" aria-live="polite"></div></div></section>';
}
function setupPortfolioExtras(host){
  var root=host.querySelector('.pf-extra');if(!root||root.dataset.ready)return;root.dataset.ready='true';
  var english=typeof currentLang!=='undefined'&&currentLang==='en',toggle=root.querySelector('.pf-multi-toggle'),options=root.querySelector('.pf-options'),chips=root.querySelector('.pf-chips');
  function close(){options.hidden=true;toggle.setAttribute('aria-expanded','false')}
  toggle.onclick=function(){options.hidden=!options.hidden;toggle.setAttribute('aria-expanded',String(!options.hidden))};
  root.addEventListener('keydown',function(e){if(e.key==='Escape'&&!options.hidden){e.preventDefault();close();toggle.focus()}});
  // Close within the form when focus or pointer moves outside this dropdown, without a modal overlay.
  if(host._pfOutside)document.removeEventListener('pointerdown',host._pfOutside);
  host._pfOutside=function(e){if(!root.isConnected){document.removeEventListener('pointerdown',host._pfOutside);return}if(!root.querySelector('.pf-multi').contains(e.target))close()};
  document.addEventListener('pointerdown',host._pfOutside);
  root.querySelector('.pf-multi').addEventListener('focusout',function(e){if(e.relatedTarget&&!this.contains(e.relatedTarget))close()});
  function sync(){chips.textContent='';var selected=Array.from(options.querySelectorAll('input:checked'));root.querySelector('#pf-areas-summary').textContent=selected.length?(english?selected.length+' selected':selected.length.toLocaleString('fa-IR')+' گزینه انتخاب شده'):(english?'Select one or more options':'یک یا چند گزینه انتخاب کنید');selected.forEach(function(input){var name=input.nextElementSibling.textContent,chip=document.createElement('span');chip.className='pf-chip';var title=document.createElement('span');title.textContent=name;var remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.setAttribute('aria-label',(english?'Remove ':'حذف ')+name);remove.onclick=function(){input.checked=false;input.dispatchEvent(new Event('change',{bubbles:true}));toggle.focus()};chip.append(title,remove);chips.appendChild(chip)})}
  options.addEventListener('change',sync);
  function digits(v){return v.replace(/[۰-۹]/g,function(c){return '۰۱۲۳۴۵۶۷۸۹'.indexOf(c)}).replace(/[٠-٩]/g,function(c){return '٠١٢٣٤٥٦٧٨٩'.indexOf(c)})}
  function validate(){var any=false,valid=true,total=[];['from','to'].forEach(function(kind){var fields=Array.from(root.querySelectorAll('[data-time="'+kind+'"]')),values=fields.map(function(f){return digits(f.value.trim())});if(values.some(Boolean))any=true;fields.forEach(function(f,i){var v=values[i],bad=!!v&&(!/^\d{1,2}$/.test(v)||+v>(i===0?23:59));f.setCustomValidity(bad?(english?'Enter a valid time':'ساعت یا دقیقه معتبر وارد کنید'):'');f.setAttribute('aria-invalid',String(bad));if(bad)valid=false});var complete=values.every(function(v){return /^\d{1,2}$/.test(v)});total.push(complete?+values[0]*60+(+values[1]):null);root.querySelector('[name="'+kind+'Time"]').value=complete&&valid?values.map(function(v){return v.padStart(2,'0')}).join(':'):''});var message='';if(!valid)message=english?'Hours: 00–23; minutes: 00–59.':'ساعت باید بین ۰۰ تا ۲۳ و دقیقه بین ۰۰ تا ۵۹ باشد.';else if(any&&total.some(function(v){return v===null})){valid=false;message=english?'Complete both start and end times.':'ساعت و دقیقهٔ شروع و پایان را کامل کنید.'}else if(any&&total[1]<total[0])message=english?'End time is on the following day.':'زمان پایان مربوط به روز بعد است.';root.querySelector('.pf-time-message').textContent=message;root.querySelector('.pf-time-message').classList.toggle('pf-error',!valid);return valid}
  root.querySelectorAll('[data-time]').forEach(function(f){f.addEventListener('input',validate);f.addEventListener('blur',function(){var v=digits(f.value.trim());if(/^\d{1,2}$/.test(v)&&+v<=(f.dataset.part==='hour'?23:59))f.value=v.padStart(2,'0');validate()})});
  var submit=host.querySelector('.pc-submit');if(submit)submit.addEventListener('click',function(e){if(!validate()){e.preventDefault();e.stopImmediatePropagation();root.querySelector('[aria-invalid="true"],[data-time]').focus()}},true);
}
