(function(){
'use strict';
var mode='classic',query='',onlyCritical=false,showLinks=true,zoom=1,selected=null,collapsed=new Set();
var names={classic:'۱. گانت مهندسی',outline:'۲. گانت سلسله‌مراتبی',focus:'۳. گانت ارتباطی'};
var descriptions={classic:'جدول تفصیلی در کنار گانت؛ برای برنامه‌ریزی دقیق و مرور ساختار شکست.',outline:'گروه‌های رنگی و ردیف‌های بازتر؛ برای تشخیص سریع والدها، فرزندان و نقاط عطف.',focus:'تمرکز روی مسیر ارتباط فعالیت‌ها؛ یک فعالیت را انتخاب کنید تا پیش‌نیاز و پس‌نیاز آن برجسته شود.'};
// Dates are offsets from 1405/07/01. Finish dates are exclusive for nonzero durations.
var tasks=[
{id:1,parent:null,wbs:'0',name:'پروژه احداث ساختمان',kind:'parent',start:0,end:90,p:34},
{id:2,parent:1,wbs:'1',name:'تحویل زمین',kind:'milestone',start:0,end:0,p:100},
{id:3,parent:1,wbs:'2',name:'پیش‌پرداخت',kind:'milestone',start:3,end:3,p:100},
{id:4,parent:1,wbs:'3',name:'ساختمان مسکونی',kind:'parent',start:3,end:90,p:33},
{id:5,parent:4,wbs:'3.1',name:'تجهیز کارگاه',kind:'child',start:3,end:12,p:100},
{id:6,parent:4,wbs:'3.2',name:'ابلاغ نقشه‌های اجرایی',kind:'milestone',start:12,end:12,p:100},
{id:7,parent:4,wbs:'3.3',name:'عملیات اجرایی',kind:'parent',start:12,end:90,p:24},
{id:8,parent:7,wbs:'3.3.1',name:'فونداسیون بلوک جنوبی',kind:'parent',start:12,end:53,p:58},
{id:9,parent:8,wbs:'3.3.1.1',name:'خاک‌برداری و رگلاژ بستر',kind:'child',start:12,end:20,p:100,critical:true},
{id:10,parent:8,wbs:'3.3.1.2',name:'اجرای بتن مگر',kind:'child',start:20,end:26,p:100,critical:true},
{id:11,parent:8,wbs:'3.3.1.3',name:'آرماتوربندی فونداسیون',kind:'child',start:26,end:41,p:55,critical:true},
{id:12,parent:8,wbs:'3.3.1.4',name:'قالب‌بندی فونداسیون',kind:'child',start:30,end:42,p:35},
{id:13,parent:8,wbs:'3.3.1.5',name:'بتن‌ریزی فونداسیون',kind:'child',start:42,end:50,p:0,critical:true},
{id:14,parent:8,wbs:'3.3.1.6',name:'تأیید فونداسیون جنوبی',kind:'milestone',start:53,end:53,p:0,critical:true},
{id:15,parent:7,wbs:'3.3.2',name:'فونداسیون بلوک شمالی',kind:'parent',start:53,end:82,p:0},
{id:16,parent:15,wbs:'3.3.2.1',name:'آرماتوربندی بلوک شمالی',kind:'child',start:53,end:68,p:0,critical:true},
{id:17,parent:15,wbs:'3.3.2.2',name:'قالب‌بندی بلوک شمالی',kind:'child',start:58,end:72,p:0},
{id:18,parent:15,wbs:'3.3.2.3',name:'بتن‌ریزی بلوک شمالی',kind:'child',start:72,end:82,p:0,critical:true},
{id:19,parent:7,wbs:'3.3.3',name:'کنترل کیفیت و تحویل سازه',kind:'child',start:82,end:90,p:0,critical:true},
{id:20,parent:1,wbs:'4',name:'تحویل موقت پروژه',kind:'milestone',start:90,end:90,p:0,critical:true}
];
var links=[{a:2,b:3,type:'FS',lag:3},{a:3,b:5,type:'FS',lag:0},{a:5,b:6,type:'FS',lag:0},{a:6,b:9,type:'FS',lag:0},{a:9,b:10,type:'FS',lag:0},{a:10,b:11,type:'FS',lag:0},{a:11,b:12,type:'SS',lag:4},{a:11,b:13,type:'FS',lag:1},{a:12,b:13,type:'FS',lag:0},{a:13,b:14,type:'FS',lag:3},{a:14,b:16,type:'FS',lag:0},{a:16,b:17,type:'SS',lag:5},{a:16,b:18,type:'FS',lag:4},{a:17,b:18,type:'FS',lag:0},{a:18,b:19,type:'FS',lag:0},{a:19,b:20,type:'FS',lag:0}];
var byId=new Map(tasks.map(function(t){return[t.id,t]}));
function fa(v){return String(v).replace(/\d/g,function(n){return '۰۱۲۳۴۵۶۷۸۹'[n]})}
function esc(v){return String(v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function icon(p){return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="'+p+'"/></svg>'}
var tabIcons=[icon('M3 5h18M3 12h9M8 19h13M3 3v18'),icon('M5 3v14h5M5 8h5M12 5h9v6h-9zM12 14h9v6h-9z'),icon('M3 4h6v6H3zM15 14h6v6h-6zM9 7h9v7M15 11l3 3 3-3')];
function date(n){return fa('1405/'+String(7+Math.floor(n/30)).padStart(2,'0')+'/'+String(n%30+1).padStart(2,'0'))}
function depth(t){var n=0;while(t.parent!==null){n++;t=byId.get(t.parent)}return n}
function ancestors(t){var a=[];while(t.parent!==null){a.push(t.parent);t=byId.get(t.parent)}return a}
tasks.filter(function(t){return t.kind==='parent'}).forEach(function(parent){var children=tasks.filter(function(t){return t.kind==='child'&&ancestors(t).includes(parent.id)}),duration=children.reduce(function(n,t){return n+t.end-t.start},0);parent.p=Math.round(children.reduce(function(n,t){return n+(t.end-t.start)*t.p},0)/(duration||1))});
function kind(t){return {parent:'والد',child:'فرزند',milestone:'مایلستون'}[t.kind]}
function visible(){var filtered=query||onlyCritical,keep=new Set();tasks.forEach(function(t){if((!query||(t.name+' '+t.wbs).includes(query))&&(!onlyCritical||t.critical)){keep.add(t.id);ancestors(t).forEach(function(id){keep.add(id)})}});return tasks.filter(function(t){return keep.has(t.id)&&(filtered||!ancestors(t).some(function(id){return collapsed.has(id)}))})}
function connected(){var ids=new Set(selected?[selected]:[]);links.forEach(function(l){if(l.a===selected||l.b===selected){ids.add(l.a);ids.add(l.b)}});return ids}
function triangle(t){return t.kind==='parent'?'<button class="sg-fold" data-fold="'+t.id+'" aria-label="'+(collapsed.has(t.id)?'بازکردن':'بستن')+' '+t.name+'" aria-expanded="'+!collapsed.has(t.id)+'">'+(collapsed.has(t.id)?'+':'−')+'</button>':'<span class="sg-node '+t.kind+'"></span>'}
function rowLabel(t){return '<div class="sg-name" style="--depth:'+depth(t)+'">'+triangle(t)+'<button class="sg-task-name" data-select="'+t.id+'" aria-pressed="'+(selected===t.id)+'">'+t.name+'</button></div>'}
function relationText(l){return l.type+(l.lag?' +'+fa(l.lag)+' روز':'')}
function detail(){var t=byId.get(selected);if(!t)return '<div class="sg-selection-empty">'+icon('M4 4h7v7H4zM13 13h7v7h-7zM11 7h6v6')+'<span>برای مشاهدهٔ جزئیات و برجسته‌شدن ارتباط‌ها، روی فعالیت یا نوار آن کلیک کنید.</span></div>';var rel=links.filter(function(l){return l.a===t.id||l.b===t.id});return '<div class="sg-selected-head"><span class="sg-type '+t.kind+'">'+kind(t)+'</span><b>'+t.name+'</b><button data-clear title="لغو انتخاب" aria-label="لغو انتخاب">×</button></div><div class="sg-detail-meta"><span>WBS <b dir="ltr">'+fa(t.wbs)+'</b></span><span>شروع <b>'+date(t.start)+'</b></span><span>پایان <b>'+date(t.end)+'</b></span><span>مدت <b>'+fa(t.end-t.start)+' روز</b></span><span>پیشرفت <b>'+fa(t.p)+'٪</b></span></div><div class="sg-relations">'+(rel.length?rel.map(function(l){var before=l.b===t.id,other=byId.get(before?l.a:l.b);return '<button data-select="'+other.id+'"><small>'+(before?'پیش‌نیاز':'پس‌نیاز')+'</small><span>'+other.name+'</span><b dir="ltr">'+relationText(l)+'</b>'+icon('M4 12h16m-5-5 5 5-5 5')+'</button>'}).join(''):'<p>'+ (t.kind==='parent'?'فعالیت خلاصه؛ بازهٔ زمانی از فعالیت‌های فرزند تشکیل شده است.':'ارتباطی برای این فعالیت ثبت نشده است.')+'</p>')+'</div>'}
function chart(){var list=visible(),rowH=mode==='classic'?39:mode==='outline'?62:54,width=zoom===1?1040:1560,pad=24,scale=(width-2*pad)/96,ids=new Map(list.map(function(t,i){return[t.id,i]})),near=connected();
function x(n){return pad+n*scale}function y(id){return ids.get(id)*rowH+rowH/2}
var paths=showLinks?links.filter(function(l){return ids.has(l.a)&&ids.has(l.b)}).map(function(l,i){var a=byId.get(l.a),b=byId.get(l.b),sx=x(l.type==='SS'?a.start:a.end),tx=x(b.start),sy=y(a.id),ty=y(b.id),mid=ty-rowH/2+4+(i%3)*3,active=selected&&(l.a===selected||l.b===selected),dim=selected&&!active;var d=l.type==='SS'?'M '+sx+' '+sy+' H '+(sx-13)+' V '+mid+' H '+(tx-13)+' V '+ty+' H '+(tx-5):'M '+sx+' '+sy+' H '+(sx+12)+' V '+mid+' H '+(tx-13)+' V '+ty+' H '+(tx-5);return '<g class="sg-link '+(active?'is-active':'')+' '+(dim?'is-muted':'')+'" data-from="'+l.a+'" data-to="'+l.b+'"><title>'+a.name+' ← '+b.name+' · '+relationText(l)+'</title><path d="'+d+'" marker-end="url(#sg-arrow'+(active?'-active':'')+')"/>'+(active||mode==='focus'?'<text x="'+(sx+16)+'" y="'+(mid-3)+'">'+l.type+(l.lag?' +'+l.lag:'')+'</text>':'')+'</g>'}).join(''):'';
var ticks='';for(var n=0;n<=90;n+=10)ticks+='<span style="left:'+x(n)+'px">'+fa(n%30+1)+'</span>';
var head=mode==='classic'?'<span>سطح</span><span>WBS</span><span>نوع ردیف</span><span>شرح فعالیت</span><span>شروع</span><span>پایان</span><span>روز</span>':'<span>ساختار شکست فعالیت‌ها <small>WBS / نوع / پیشرفت</small></span>';
var meta=list.map(function(t){return '<div class="sg-meta-row '+t.kind+' '+(selected===t.id?'is-selected':'')+'" data-row="'+t.id+'">'+(mode==='classic'?'<span>'+fa(depth(t))+'</span><span class="sg-wbs" dir="ltr">'+fa(t.wbs)+'</span><span class="sg-type '+t.kind+'">'+kind(t)+'</span>'+rowLabel(t)+'<span class="sg-date">'+date(t.start)+'</span><span class="sg-date">'+date(t.end)+'</span><span>'+fa(t.end-t.start)+'</span>':'<div class="sg-outline-label">'+rowLabel(t)+'<div class="sg-outline-meta"><span dir="ltr">'+fa(t.wbs)+'</span><span class="sg-type '+t.kind+'">'+kind(t)+'</span><span>'+fa(t.end-t.start)+' روز</span><b>'+fa(t.p)+'٪</b></div></div>')+'</div>'}).join('');
var bars=list.map(function(t){var pos=x(t.start),barWidth=Math.max(3,(t.end-t.start)*scale),dim=selected&&!near.has(t.id)&&t.kind!=='parent';return '<div class="sg-timeline-row '+t.kind+' '+(selected===t.id?'is-selected':'')+'" style="top:'+(ids.get(t.id)*rowH)+'px"></div><button class="sg-bar '+t.kind+' '+(t.p===100?'complete':'')+' '+(t.critical?'critical':'')+' '+(selected===t.id?'is-selected':'')+' '+(dim?'is-muted':'')+'" data-select="'+t.id+'" aria-pressed="'+(selected===t.id)+'" aria-label="'+t.name+'، '+kind(t)+'، '+fa(t.p)+' درصد" title="'+t.name+' · '+kind(t)+' · '+fa(t.p)+'٪" style="left:'+pos+'px;top:'+(y(t.id))+'px;'+(t.kind==='milestone'?'':'width:'+barWidth+'px')+'">'+(t.kind==='milestone'?'<i class="sg-diamond"></i>':t.kind==='parent'?'<i class="sg-summary"></i>':'<i class="sg-progress" style="width:'+t.p+'%"></i>')+'<span class="sg-bar-label">'+(mode==='classic'&&t.kind==='child'?fa(t.p)+'٪':t.name)+'</span></button>'}).join('');
return '<div class="sg-scroll" tabindex="0" aria-label="جدول و گانت؛ پیمایش افقی و عمودی"><div class="sg-board sg-'+mode+'" style="--row-h:'+rowH+'px;--timeline-w:'+width+'px"><div class="sg-meta"><div class="sg-meta-head">'+head+'</div>'+meta+'</div><div class="sg-timeline"><div class="sg-time-head"><div class="sg-months" style="padding-left:'+pad+'px;padding-right:'+pad+'px"><span>مهر ۱۴۰۵</span><span>آبان ۱۴۰۵</span><span>آذر ۱۴۰۵</span><span>دی</span></div><div class="sg-ticks">'+ticks+'</div></div><div class="sg-time-body" style="height:'+(list.length*rowH)+'px;background-size:'+(10*scale)+'px 100%;background-position-x:'+pad+'px">'+bars+'<div class="sg-report-line" style="left:'+x(35)+'px"><span>۶ آبان · تاریخ گزارش</span></div><svg class="sg-links" width="'+width+'" height="'+(list.length*rowH)+'" aria-label="ارتباط فعالیت‌ها"><defs><marker id="sg-arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0L6 3L0 6Z" fill="#ff8868"/></marker><marker id="sg-arrow-active" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7Z" fill="#6859cf"/></marker></defs>'+paths+'</svg></div></div></div>'+(list.length?'':'<p class="sg-empty">فعالیتی با این جستجو پیدا نشد.</p>')+'</div><div class="sg-chart-footer"><span>'+fa(list.length)+' ردیف قابل مشاهده از '+fa(tasks.length)+'</span><span>FS پایان به شروع · SS شروع به شروع · + تأخیر رابطه</span></div>'}
function render(){var panel=document.getElementById('sg-content');if(!panel)return;var scroll=panel.querySelector('.sg-scroll'),sx=scroll?scroll.scrollLeft:0,sy=scroll?scroll.scrollTop:0;panel.closest('.sg-shell').dataset.mode=mode;panel.innerHTML=chart();panel.setAttribute('aria-labelledby','sg-tab-'+mode);var next=panel.querySelector('.sg-scroll');next.scrollLeft=sx;next.scrollTop=sy;document.getElementById('sg-description').textContent=descriptions[mode];document.getElementById('sg-detail').innerHTML=detail();document.querySelectorAll('[data-sg-tab]').forEach(function(b){var active=b.dataset.sgTab===mode;b.classList.toggle('active',active);b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1})}
window.buildScheduleGrid=function(){return '<section class="sg-shell" data-mode="'+mode+'" dir="rtl"><header class="sg-heading"><div><span class="sg-eyebrow">پروژه احداث ساختمان / برنامهٔ مبنا</span><h2>زمان‌بندی و گانت</h2></div><div class="sg-heading-meta"><span class="sg-demo">داده‌های نمونه</span><span>۲۰ ردیف <i>•</i> ۱۶ ارتباط <i>•</i> ۹۰ روز</span></div></header><nav class="group-tabs sg-tabs" role="tablist" aria-label="سه طراحی زمان‌بندی">'+Object.keys(names).map(function(k,i){return '<button type="button" id="sg-tab-'+k+'" role="tab" data-sg-tab="'+k+'" class="group-tab gt-blue '+(mode===k?'active':'')+'" aria-selected="'+(mode===k)+'" aria-controls="sg-content" tabindex="'+(mode===k?'0':'-1')+'"><span class="parameter-tab-icon">'+tabIcons[i]+'</span>'+names[k]+'</button>'}).join('')+'</nav><div class="sg-design-intro"><p id="sg-description">'+descriptions[mode]+'</p><div class="sg-legend"><span><i class="parent"></i>والد / فعالیت خلاصه</span><span><i class="child"></i>فرزند / فعالیت اجرایی</span><span><i class="milestone"></i>مایلستون / مدت صفر</span><span><i class="complete"></i>تکمیل‌شده</span><span><i class="relation"></i>ارتباط فعالیت‌ها</span><span><i class="critical"></i>بحرانی</span></div></div><div class="sg-toolbar"><label class="sg-search">'+icon('M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0')+'<input id="sg-search" type="search" aria-label="جستجوی شرح یا WBS" placeholder="جستجوی شرح یا WBS…" value="'+esc(query)+'"></label><button data-expand="open" title="بازکردن تمام والدها">'+icon('M4 7h16M4 17h16M12 2v9m-3-3 3 3 3-3M12 22v-9m-3 3 3-3 3 3')+'بازکردن همه</button><button data-expand="close" title="بستن تمام والدها">'+icon('M4 12h16M12 2v6m-3-3 3 3 3-3M12 22v-6m-3 3 3-3 3 3')+'بستن همه</button><label><input type="checkbox" id="sg-critical" '+(onlyCritical?'checked':'')+'> مسیر بحرانی نمونه</label><label><input type="checkbox" id="sg-links-toggle" '+(showLinks?'checked':'')+'> نمایش ارتباط‌ها</label><button id="sg-zoom">'+icon('M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0M6 10h8M10 6v8')+'بزرگ‌نمایی</button></div><section id="sg-content" role="tabpanel" aria-labelledby="sg-tab-'+mode+'" tabindex="0">'+chart()+'</section><aside id="sg-detail" class="sg-detail" aria-label="جزئیات و ارتباط فعالیت انتخاب‌شده" aria-live="polite">'+detail()+'</aside><footer class="sg-foot">تقویم شمسی · محور زمان از چپ به راست <span>والدها از فرزندان جمع‌بندی می‌شوند؛ مسیر بحرانی در این نمونه از پیش مشخص شده است.</span></footer></section>'};
document.addEventListener('click',function(e){var shell=e.target.closest('.sg-shell');if(!shell)return;var tab=e.target.closest('[data-sg-tab]');if(tab){mode=tab.dataset.sgTab;render();return}var fold=e.target.closest('[data-fold]');if(fold){var id=+fold.dataset.fold;collapsed.has(id)?collapsed.delete(id):collapsed.add(id);render();var replacement=shell.querySelector('[data-fold="'+id+'"]');if(replacement)replacement.focus();return}var task=e.target.closest('[data-select]');if(task){selected=+task.dataset.select;ancestors(byId.get(selected)).forEach(function(id){collapsed.delete(id)});render();return}if(e.target.closest('[data-clear]')){selected=null;render();return}var all=e.target.closest('[data-expand]');if(all){collapsed=all.dataset.expand==='open'?new Set():new Set(tasks.filter(function(t){return t.kind==='parent'}).map(function(t){return t.id}));render();return}if(e.target.closest('#sg-zoom')){zoom=zoom===1?1.5:1;render();document.getElementById('sg-zoom').innerHTML=tabIcons[0]+(zoom===1?'بزرگ‌نمایی':'نمای فشرده')}});
document.addEventListener('input',function(e){if(e.target.id==='sg-search'){query=e.target.value.trim().replace(/[۰-۹]/g,function(n){return '۰۱۲۳۴۵۶۷۸۹'.indexOf(n)});render()}});
document.addEventListener('change',function(e){if(e.target.id==='sg-critical'){onlyCritical=e.target.checked;render()}if(e.target.id==='sg-links-toggle'){showLinks=e.target.checked;render()}});
document.addEventListener('keydown',function(e){if(!e.target.closest('[data-sg-tab]'))return;var keys=Object.keys(names),i=keys.indexOf(mode);if(e.key==='ArrowLeft')i=(i+1)%3;else if(e.key==='ArrowRight')i=(i+2)%3;else if(e.key==='Home')i=0;else if(e.key==='End')i=2;else return;e.preventDefault();mode=keys[i];render();document.getElementById('sg-tab-'+mode).focus()});
})();
