(function(){
  'use strict';
  var mode='table', query='', critical=false, zoom=1;
  var tasks=[
    {id:1,wbs:'1.1',name:'تجهیز و آماده‌سازی کارگاه',owner:'واحد اجرا',phase:0,start:0,end:12,progress:100,plan:100,critical:false},
    {id:2,wbs:'1.2',name:'عملیات خاک‌برداری و تسطیح',owner:'گروه عملیات خاکی',phase:0,start:8,end:27,progress:100,plan:100,critical:true},
    {id:3,wbs:'2.1',name:'اجرای فونداسیون و بتن مگر',owner:'گروه سازه',phase:1,start:23,end:44,progress:76,plan:90,critical:true},
    {id:4,wbs:'2.2',name:'آرماتوربندی و قالب‌بندی',owner:'گروه سازه',phase:1,start:36,end:61,progress:42,plan:60,critical:true},
    {id:5,wbs:'2.3',name:'بتن‌ریزی عرشه',owner:'واحد اجرا',phase:1,start:55,end:76,progress:0,plan:0,critical:true},
    {id:6,wbs:'3.1',name:'اجرای تأسیسات و زهکشی',owner:'گروه تأسیسات',phase:2,start:49,end:75,progress:18,plan:25,critical:false},
    {id:7,wbs:'3.2',name:'روسازی و تکمیل مسیر',owner:'گروه راه‌سازی',phase:2,start:73,end:91,progress:0,plan:0,critical:true},
    {id:8,wbs:'3.3',name:'کنترل کیفیت و تحویل موقت',owner:'دستگاه نظارت',phase:2,start:90,end:100,progress:0,plan:0,critical:true}
  ];
  var phases=['آماده‌سازی','اجرای سازه','تکمیل و تحویل'];
  var titles={table:'گانت جدولی',roadmap:'نقشهٔ راه',control:'کنترل پیشرفت'};
  function fa(v){return String(v).replace(/\d/g,function(n){return '۰۱۲۳۴۵۶۷۸۹'[n]})}
  function esc(v){return String(v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function icon(path){return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="'+path+'"/></svg>'}
  var icons=[icon('M4 5h16M4 12h9M9 19h11M4 3v18'),icon('M5 5h14v5H5zM5 14h14v5H5zM12 10v4'),icon('M4 19V5M4 19h16M8 15l4-6 4 3 4-7')];
  function date(day){return fa('۱۴۰۵/'+(day<30?'۰۷/':day<60?'۰۸/':day<90?'۰۹/':'۱۰/')+String(day<30?day+1:day<60?day-29:day<90?day-59:day-89).padStart(2,'0'))}
  function filtered(){return tasks.filter(function(t){return (!critical||t.critical)&&(!query||(t.name+' '+t.owner+' '+t.wbs).includes(query))})}
  function state(t){return t.progress===100?'تکمیل‌شده':t.progress<t.plan?'عقب‌تر از برنامه':t.progress?'در حال اجرا':'شروع‌نشده'}
  function color(t){return t.progress===100?'done':t.progress<t.plan?'late':t.progress?'running':'pending'}
  function badge(t){return '<span class="sg-badge '+color(t)+'">'+state(t)+'</span>'}
  function details(t){return '<button type="button" class="sg-detail" data-task="'+t.id+'" title="جزئیات '+esc(t.name)+'" aria-label="جزئیات '+esc(t.name)+'">'+icon('M12 8h.01M11 12h1v5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0')+'</button>'}
  function bar(t){return '<button type="button" data-task="'+t.id+'" class="sg-bar '+color(t)+'" style="inset-inline-start:'+t.start+'%;width:'+(t.end-t.start)+'%" title="'+esc(t.name)+' · '+fa(t.progress)+'٪" aria-label="'+esc(t.name)+'، پیشرفت '+fa(t.progress)+' درصد"><i style="width:'+t.progress+'%"></i><span>'+fa(t.progress)+'٪</span></button>'}
  function axis(){return '<div class="sg-axis"><span>مهر ۱۴۰۵</span><span>آبان</span><span>آذر</span><span>دی</span></div>'}
  function table(list){return '<div class="sg-chart-scroll"><div class="sg-grid" style="min-width:'+(zoom===1?990:1450)+'px"><div class="sg-grid-head"><span>ساختار شکست / فعالیت</span><span>پیشرفت</span><span>مدت</span>'+axis()+'<span></span></div>'+list.map(function(t){return '<div class="sg-grid-row"><div class="sg-task"><small>'+fa(t.wbs)+'</small><div><b>'+t.name+'</b><span>'+t.owner+'</span></div>'+(t.critical?'<i class="sg-critical" title="فعالیت بحرانی"></i>':'')+'</div><div>'+badge(t)+'<small class="sg-percent">'+fa(t.progress)+'٪</small></div><span>'+fa(t.end-t.start)+' روز</span><div class="sg-track"><div class="sg-reference"></div>'+bar(t)+'</div>'+details(t)+'</div>'}).join('')+'</div></div><div class="sg-legend"><span><i class="done"></i>تکمیل‌شده</span><span><i class="running"></i>در حال اجرا</span><span><i class="late"></i>عقب‌تر از برنامه</span><span><i class="pending"></i>شروع‌نشده</span><span>خط گزارش: ۱۸ آبان ۱۴۰۵</span></div>'}
  function roadmap(list){return '<div class="sg-roadmap">'+phases.map(function(p,i){var items=list.filter(function(t){return t.phase===i});return '<section class="sg-phase"><header><span class="sg-phase-no">'+fa(i+1)+'</span><div><h3>'+p+'</h3><small>'+['مهر · آماده‌سازی بستر اجرا','مهر تا آذر · مسیر اصلی پروژه','آبان تا دی · تکمیل عملیات'][i]+'</small></div><span class="sg-phase-count">'+fa(items.length)+' فعالیت</span></header><div class="sg-phase-body">'+items.map(function(t){return '<article class="sg-task-card '+color(t)+'"><div class="sg-card-top"><small>WBS '+fa(t.wbs)+'</small>'+details(t)+'</div><h4>'+t.name+'</h4><p>'+t.owner+'</p><div class="sg-card-status">'+badge(t)+'<b>'+fa(t.progress)+'٪</b></div><div class="sg-meter"><i style="width:'+t.progress+'%"></i></div><footer><span>'+date(t.start)+' ← '+date(t.end)+'</span><span>'+fa(t.end-t.start)+' روز</span></footer></article>'}).join('')+(items.length?'':'<p class="sg-empty">فعالیتی با این فیلتر وجود ندارد.</p>')+'</div><div class="sg-phase-end">◇ '+['پایان عملیات خاکی','تکمیل سازه','تحویل موقت'][i]+'</div></section>'}).join('')+'</div>'}
  function control(list){return '<div class="sg-control"><section class="sg-comparison"><header><h3>برنامه در برابر عملکرد</h3><span>درصد تکمیل هر فعالیت</span></header><div class="sg-legend"><span><i class="pending"></i>برنامه‌ای</span><span><i class="running"></i>واقعی</span></div>'+list.map(function(t){return '<div class="sg-compare-row"><div><b>'+t.name+'</b><small>'+t.owner+'</small></div><div class="sg-double"><div><i style="width:'+t.plan+'%"></i><span>'+fa(t.plan)+'٪</span></div><div class="actual '+color(t)+'"><i style="width:'+t.progress+'%"></i><span>'+fa(t.progress)+'٪</span></div></div>'+details(t)+'</div>'}).join('')+'</section><aside class="sg-insights"><h3>نیازمند توجه</h3><p>فعالیت‌هایی که از برنامه عقب‌تر هستند</p>'+list.filter(function(t){return t.progress<t.plan}).sort(function(a,b){return (b.plan-b.progress)-(a.plan-a.progress)}).map(function(t){return '<article><div class="sg-insight-title"><b>'+t.name+'</b>'+details(t)+'</div><strong>'+fa(t.plan-t.progress)+' واحد درصد</strong><span>فاصله با پیشرفت برنامه‌ای</span><small>'+t.owner+(t.critical?' · فعالیت بحرانی':'')+'</small></article>'}).join('')+'<div class="sg-note">مبنای مقایسه<br><b>گزارش ۱۸ آبان ۱۴۰۵</b><br>درصدها برای نمایش طراحی هستند.</div></aside></div>'}
  function content(){var list=filtered(),el=document.getElementById('sg-content');if(!el)return;el.innerHTML=list.length?(mode==='table'?table(list):mode==='roadmap'?roadmap(list):control(list)):'<div class="sg-empty">فعالیتی پیدا نشد. جستجو یا فیلتر را تغییر دهید.</div>';el.setAttribute('aria-labelledby','sg-tab-'+mode);document.getElementById('sg-count').textContent=fa(list.length)+' فعالیت';document.querySelectorAll('[data-sg-tab]').forEach(function(b){var on=b.dataset.sgTab===mode;b.classList.toggle('active',on);b.setAttribute('aria-selected',on);b.tabIndex=on?0:-1});var z=document.getElementById('sg-zoom');if(z)z.hidden=mode!=='table'}
  window.buildScheduleGrid=function(){return '<section class="sg-shell" dir="rtl"><div class="sg-heading"><div><span class="sg-eyebrow">برنامهٔ اجرایی / نسخهٔ مبنا</span><h2>زمان‌بندی و گانت</h2><p>از تصویر کلی پروژه تا جزئیات هر فعالیت</p></div><span class="sg-demo">پیش‌نمایش طراحی · داده‌های نمونه</span></div><div class="sg-stats"><div><span>فعالیت‌های برنامه</span><b>۸ <small>فعالیت</small></b></div><div><span>تکمیل‌شده</span><b>۲ <small>از ۸ فعالیت</small></b></div><div><span>نیازمند توجه</span><b class="sg-warn">۳ <small>فعالیت</small></b></div><div><span>افق برنامه</span><b>۱۰۰ <small>روز</small></b></div></div><nav class="group-tabs sg-tabs" role="tablist" aria-label="طرح‌های زمان‌بندی">'+Object.keys(titles).map(function(k,i){return '<button type="button" id="sg-tab-'+k+'" class="group-tab gt-blue '+(mode===k?'active':'')+'" role="tab" data-sg-tab="'+k+'" aria-controls="sg-content" aria-selected="'+(mode===k)+'" tabindex="'+(mode===k?'0':'-1')+'"><span class="parameter-tab-icon">'+icons[i]+'</span>'+titles[k]+'</button>'}).join('')+'</nav><div class="sg-toolbar"><label class="sg-search">'+icon('M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0')+'<input type="search" id="sg-search" aria-label="جستجوی فعالیت" placeholder="جستجوی فعالیت یا مسئول…" value="'+esc(query)+'"></label><label class="sg-filter"><input id="sg-critical" type="checkbox" '+(critical?'checked':'')+'> فقط فعالیت‌های بحرانی</label><button type="button" id="sg-zoom" class="sg-zoom" '+(mode!=='table'?'hidden':'')+'>بزرگ‌نمایی گانت</button><span id="sg-count">'+fa(filtered().length)+' فعالیت</span></div><div id="sg-content" role="tabpanel" tabindex="0" aria-labelledby="sg-tab-'+mode+'">'+(mode==='table'?table(filtered()):mode==='roadmap'?roadmap(filtered()):control(filtered()))+'</div><footer class="sg-foot">تقویم شمسی <span>واحد مدت: روز تقویمی · برنامهٔ نمونه برای مقایسهٔ سه طراحی</span></footer></section>'};
  document.addEventListener('click',function(e){var tab=e.target.closest('[data-sg-tab]');if(tab){mode=tab.dataset.sgTab;content();return}if(e.target.closest('#sg-zoom')){zoom=zoom===1?2:1;content();document.getElementById('sg-zoom').textContent=zoom===1?'بزرگ‌نمایی گانت':'نمای فشرده';return}var btn=e.target.closest('[data-task]');if(!btn||!btn.closest('.sg-shell'))return;var t=tasks.find(function(x){return x.id===+btn.dataset.task});if(!t)return;var old=document.getElementById('sg-dialog');if(old)old.remove();var dialog=document.createElement('dialog');dialog.id='sg-dialog';dialog.className='sg-dialog';dialog.dir='rtl';dialog.innerHTML='<form method="dialog"><button class="sg-dialog-close" aria-label="بستن">×</button></form><span class="sg-eyebrow">جزئیات فعالیت · WBS '+fa(t.wbs)+'</span><h2>'+t.name+'</h2>'+badge(t)+'<dl><dt>مسئول اجرا</dt><dd>'+t.owner+'</dd><dt>شروع</dt><dd>'+date(t.start)+'</dd><dt>پایان</dt><dd>'+date(t.end)+'</dd><dt>پیشرفت واقعی / برنامه‌ای</dt><dd>'+fa(t.progress)+'٪ / '+fa(t.plan)+'٪</dd><dt>فعالیت بحرانی</dt><dd>'+(t.critical?'بله':'خیر')+'</dd></dl><p class="sg-note">اطلاعات نمونه برای بررسی طراحی</p>';document.body.appendChild(dialog);dialog.addEventListener('close',function(){dialog.remove();btn.focus()});dialog.showModal()});
  document.addEventListener('input',function(e){if(e.target.id==='sg-search'){query=e.target.value.trim();content()}});
  document.addEventListener('change',function(e){if(e.target.id==='sg-critical'){critical=e.target.checked;content()}});
  document.addEventListener('keydown',function(e){var b=e.target.closest('[data-sg-tab]');if(!b)return;var keys=Object.keys(titles),i=keys.indexOf(mode);if(e.key==='ArrowLeft')i=(i+1)%3;else if(e.key==='ArrowRight')i=(i+2)%3;else if(e.key==='Home')i=0;else if(e.key==='End')i=2;else return;e.preventDefault();mode=keys[i];content();document.getElementById('sg-tab-'+mode).focus()});
})();
