(function(){
 'use strict';
 var panel,user,action,sub='allowed',trigger,ipRows={},changes={};
 var titles={'related-0':'نقش‌های مربوطه','related-1':'تاریخچه ورود','related-2':'تاریخچه تغییرات','operation-0':'مشاهده کاربر','operation-1':'ویرایش کاربر','operation-2':'محدودیت IP'};
 function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
 function table(headers,rows){return '<div class="pud-table"><table class="psub-table"><thead><tr>'+headers.map(function(h){return '<th>'+h+'</th>'}).join('')+'</tr></thead><tbody>'+(rows.length?rows.map(function(r){return '<tr>'+r.map(function(c){return '<td>'+esc(c)+'</td>'}).join('')+'</tr>'}).join(''):'<tr><td colspan="'+headers.length+'">داده‌ای برای نمایش وجود ندارد.</td></tr>')+'</tbody></table></div>'}
 function field(label,name,value,readonly){return '<label>'+label+'<input name="'+name+'" value="'+esc(value)+'" '+(readonly?'readonly':'required')+'></label>'}
 function tabs(values){return '<nav class="pud-tabs">'+values.map(function(v){return '<button type="button" class="group-tab'+(sub===v[0]?' active':'')+'" aria-selected="'+(sub===v[0])+'" data-sub="'+v[0]+'">'+v[1]+'</button>'}).join('')+'</nav>'}
 function close(){if(panel)panel.remove();panel=null;if(trigger&&trigger.isConnected)trigger.focus({preventScroll:true})}
 function render(){var content='',edit=action==='operation-1';
  if(action==='operation-0'||edit){content='<form data-form="user"><div class="pud-fields">'+field('نام','first',user[1],!edit)+field('نام خانوادگی','last',user[2],!edit)+field('نام کاربری','username',user[3],!edit)+field('نوع لایسنس','license',user[7],!edit)+'<label>وضعیت<select name="status" '+(!edit?'disabled':'')+'><option '+(user[6]==='فعال'?'selected':'')+'>فعال</option><option '+(user[6]!=='فعال'?'selected':'')+'>غیر فعال</option></select></label>'+field('تاریخ ایجاد','created',user[4],true)+field('تاریخ آخرین ورود','lastLogin',user[5],true)+field('کد فعال‌سازی','activation','—',true)+'</div>'+(edit?'<footer><button type="submit" class="pud-save">ثبت تغییرات نمونه</button></footer>':'')+'</form>'}
  if(action==='related-0')content=table(['سازمان مربوطه','نام','وضعیت نقش','وضعیت نقش کاربر'],[]);
  if(action==='related-1')content=tabs([['success','ورود موفق'],['failed','ورود ناموفق']])+table(['ردیف','IP','زمان (تاریخ و ساعت)'].concat(sub==='failed'?['پیام خطا']:[]),[]);
  if(action==='related-2'){var log=changes[user[0]]||[];content=table(['ردیف','موجودیت','شناسه داده','زمان','عملیات'],log.map(function(x,i){return [i+1,'کاربران',user[3],x.time,'ویرایش نمونه']}))+'<h3>جزئیات تغییرات همین نشست</h3>'+table(['نام فیلد','داده قبلی','داده جدید'],log.length?log[log.length-1].details:[])}
  if(action==='operation-2'){var rows=(ipRows[user[0]]||[]).filter(function(x){return x.kind===sub});content=tabs([['allowed','IPهای مجاز'],['blocked','IPهای مسدود']])+table(['ردیف','IP از','IP تا','mask','تاریخ شروع','تاریخ پایان','وضعیت'],rows.map(function(x,i){return [i+1,x.from,x.to||'—',x.mask||'—',x.start||'—',x.end||'—',x.active?'فعال':'غیرفعال']}))+'<h3>افزودن '+(sub==='allowed'?'IP مجاز':'IP مسدود')+'</h3><form data-form="ip"><label class="pud-check"><input name="range" type="checkbox"> بر اساس محدوده</label><div class="pud-fields">'+field('IP / از','from','',false)+'<label data-range hidden>تا<input name="to" dir="ltr"></label><label>mask (اختیاری)<input name="mask" dir="ltr" placeholder="255.255.255.0"></label>'+['start','end'].map(function(k){return '<label>تاریخ '+(k==='start'?'شروع':'پایان')+'<span class="pud-date"><input name="'+k+'" placeholder="1405/06/09" dir="ltr"><button type="button" data-date="'+k+'" aria-label="انتخاب تاریخ '+(k==='start'?'شروع':'پایان')+'">▦</button></span></label>'}).join('')+'<label class="pud-check"><input name="active" type="checkbox" checked> فعال</label></div><p class="pud-error" role="alert"></p><footer><button type="submit" class="pud-save">افزودن به نمونه</button></footer></form>'}
  panel.innerHTML='<header><div><h2>'+titles[action]+'</h2><span>'+esc(user[1]+' '+user[2])+' · '+esc(user[3])+'</span></div><button type="button" data-close aria-label="بستن پنل">×</button></header><p class="pud-note">نمونه طراحی؛ داده‌ها و تغییرات فقط در این نشست هستند. '+(action==='operation-2'?'هیچ محدودیت واقعی بر ورود اعمال نمی‌شود.':'سوابق سرور هنوز متصل نیست.')+'</p><div class="pud-body">'+content+'</div>';
  panel.querySelector('[data-close]').onclick=close;panel.querySelectorAll('[data-sub]').forEach(function(b){b.onclick=function(){sub=b.dataset.sub;render()}});
  panel.querySelectorAll('[data-date]').forEach(function(b){b.onclick=function(){if(window.openParameterDatePicker)window.openParameterDatePicker(panel.querySelector('[name="'+b.dataset.date+'"]'))}});
  var form=panel.querySelector('form');if(!form)return;
  if(action==='operation-2')form.elements.range.onchange=function(){form.querySelector('[data-range]').hidden=!this.checked;form.elements.to.required=this.checked};
  form.onsubmit=function(e){e.preventDefault();var f=form.elements;if(edit){var detail=[];[['first',1,'نام'],['last',2,'نام خانوادگی'],['username',3,'نام کاربری'],['license',7,'نوع لایسنس'],['status',6,'وضعیت']].forEach(function(x){var v=f[x[0]].value.trim();if(v!==user[x[1]]){detail.push([x[2],user[x[1]],v]);user[x[1]]=v}});if(detail.length)(changes[user[0]]||(changes[user[0]]=[])).push({time:new Date().toLocaleString('fa-IR'),details:detail});if(window.renderPeopleSub)window.renderPeopleSub();close();return}
   var valid=function(s){return /^(\d{1,3}\.){3}\d{1,3}$/.test(s)&&s.split('.').every(function(n){return +n<=255})},num=function(s){return s.split('.').reduce(function(n,x){return n*256+(+x)},0)};var from=f.from.value.trim(),to=f.range.checked?f.to.value.trim():'',mask=f.mask.value.trim(),error='';if(!valid(from)||(to&&(!valid(to)||num(to)<num(from)))||(f.range.checked&&!to))error='IPv4 معتبر وارد کنید؛ انتهای محدوده نباید قبل از شروع باشد.';else if(mask&&(!valid(mask)||!/^(1*)(0*)$/.test(mask.split('.').map(function(x){return (+x).toString(2).padStart(8,'0')}).join(''))))error='ماسک شبکه معتبر وارد کنید.';else if([f.start.value,f.end.value].some(function(v){return v&&!/^1[34]\d{2}\/(0[1-9]|1[0-2])\/(0[1-9]|[12]\d|3[01])$/.test(v)}))error='تاریخ را با قالب 1405/06/09 وارد کنید.';else if(f.start.value&&f.end.value&&f.end.value<f.start.value)error='تاریخ پایان نباید قبل از شروع باشد.';if(error){form.querySelector('.pud-error').textContent=error;return}(ipRows[user[0]]||(ipRows[user[0]]=[])).push({kind:sub,from:from,to:to,mask:mask,start:f.start.value,end:f.end.value,active:f.active.checked});render();
  };
 }
 document.addEventListener('click',function(e){var b=e.target.closest('[data-user-action]');if(!b||!b.closest('.parameter-users-full'))return;e.preventDefault();e.stopImmediatePropagation();var found=window.PS_USERS&&PS_USERS.find(function(r){return String(r[0])===b.dataset.userId});if(!found)return;close();trigger=b;user=found;action=b.dataset.userAction;sub=action==='related-1'?'success':'allowed';panel=document.createElement('aside');panel.className='parameter-user-drawer';panel.setAttribute('aria-label',titles[action]);panel.setAttribute('dir','rtl');(document.getElementById('app-shell')||document.body).appendChild(panel);render();panel.querySelector('[data-close]').focus({preventScroll:true})},true);
 document.addEventListener('keydown',function(e){if(e.key==='Escape'&&panel&&!document.querySelector('.parameter-date-overlay.open'))close()});
})();
